### Edit PORT number in this line 
@BASE_URL= http://localhost:3000


### Add an user
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name": "Jessica Sage"
}


### Update user name
PATCH {{BASE_URL}}/users/1
Content-Type: application/json

{
    "name": "Jimmy Page - modified"
}


### Add contact 1 to user 1 list
POST {{BASE_URL}}/contacts/2
Content-Type: application/json

{
    "name": "Samantha",
    "last_name": "Doe",
    "email": "sam@gmail.com",
    "phone_number": 600000521
}


### Add contact 2 to user 1 list
POST {{BASE_URL}}/contacts/2
Content-Type: application/json

{
    "name": "John",
    "last_name": "Doe",
    "email": "john@gmail.com",
    "phone_number": 600000000
}


### Delete contact 1
DELETE {{BASE_URL}}/contacts/1


### Recover contact 1
PATCH {{BASE_URL}}/contacts/1/recover


### Update contact 2 data
PUT {{BASE_URL}}/contacts/3
Content-Type: application/json

{
    "name": "John",
    "last_name": "Doe edited",
    "email": "john_doe@gmail.com",
    "phone_number": 600000000
}


### Mark as favorite contact 2
PATCH {{BASE_URL}}/contacts/2/favorites


### Show a list with all the contacts of User 2 order by alphabet
GET {{BASE_URL}}/contacts/2

### Show User 1 favorites contacts
GET {{BASE_URL}}/contacts/1/favorites

### Show user 2 Deleted contacts list
GET {{BASE_URL}}/contacts/1/deleted