### Edit PORT number in this line 
@BASE_URL= http://localhost:3000
### Add contact 1
POST {{BASE_URL}}/contacts
Content-Type: application/json

{
    "name": "Samantha",
    "last_name": "Doe",
    "email": "sam_doe@gmail.com",
    "phone_number": 600000021
}


### Add Contact 2
POST {{BASE_URL}}/contacts
Content-Type: application/json

{
    "name": "Jhon",
    "last_name": "Doe",
    "email": "jon_doe@gmail.com",
    "phone_number": 600000000
}


### Delete contact 1
DELETE {{BASE_URL}}/contacts/1


### Update contact 2 data
PUT {{BASE_URL}}/contacts/2
Content-Type: application/json

{
    "name": "Jhon",
    "last_name": "Doe edited",
    "email": "jon_doe@gmail.com",
    "phone_number": 600000000
}


### Mark contact 2 as favorite
PATCH {{BASE_URL}}/contacts/2/favorites


### Recover contact 1
PATCH {{BASE_URL}}/contacts/2/recover


### Show contacts list
GET {{BASE_URL}}/contacts

